tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#cdbdff",
        "surface-container-highest": "#2f3446",
        "secondary-fixed-dim": "#75d1ff",
        tertiary: "#00e1a5",
        "surface-bright": "#34394a",
        "primary-container": "#7c4dff",
        "on-primary-fixed-variant": "#4f00d0",
        "secondary-fixed": "#c2e8ff",
        "tertiary-container": "#00825e",
        "on-secondary-fixed-variant": "#004d67",
        "tertiary-fixed": "#43ffc0",
        surface: "#0e1323",
        "on-error": "#690005",
        "surface-container": "#1a1f30",
        "on-primary-fixed": "#20005f",
        "on-tertiary-container": "#e2ffef",
        "surface-container-low": "#161b2b",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dee1f9",
        "on-secondary": "#003548",
        "primary-fixed": "#e8deff",
        "on-surface": "#dee1f9",
        "on-secondary-fixed": "#001e2b",
        "surface-variant": "#2f3446",
        "on-primary-container": "#fcf6ff",
        "surface-container-high": "#25293a",
        "on-secondary-container": "#004b65",
        "on-background": "#dee1f9",
        "surface-container-lowest": "#080d1d",
        "on-tertiary": "#003827",
        "error-container": "#93000a",
        "inverse-on-surface": "#2b3041",
        error: "#ffb4ab",
        background: "#0e1323",
        "inverse-primary": "#6833ea",
        secondary: "#8fd8ff",
        "secondary-container": "#00c1fd",
        "surface-dim": "#0e1323",
        "on-surface-variant": "#cac3d8",
        "outline-variant": "#494455",
        "tertiary-fixed-dim": "#00e1a5",
        primary: "#cdbdff",
        "on-tertiary-fixed-variant": "#005139",
        "surface-tint": "#cdbdff",
        "on-primary": "#370096",
        "on-tertiary-fixed": "#002115",
        outline: "#948ea1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "20px",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        "container-max": "1200px",
        xl: "80px",
        base: "8px",
        md: "24px",
        gutter: "24px",
        sm: "12px",
        lg: "48px",
      },
      fontFamily: {
        "headline-md": ["Geist"],
        "headline-lg": ["Geist"],
        "label-md": ["Geist"],
        "headline-xl": ["Geist"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Geist"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
};
